# Generated by Django 4.0.6 on 2022-12-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0002_rename_student_registration_detail_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_detail',
            old_name='place_of_residence',
            new_name='city_of_residence',
        ),
    ]
