# Generated by Django 4.0.6 on 2022-12-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0004_alter_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.FileField(upload_to=''),
        ),
    ]
